// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from 'dotenv'
import { defineConfig } from 'prisma/config'

// Load env files from both possible working directories:
// - backend/.env when commands are run inside backend
// - backend/.env when commands are run from the project root with npm --prefix backend
config({ path: '.env' })
config({ path: 'backend/.env' })

const databaseUrl = process.env['DATABASE_URL']

export default defineConfig({
  schema: 'src/prisma/schema.prisma',
  migrations: {
    path: 'src/prisma/migrations',
  },
  datasource: {
    url: databaseUrl,
  },
})
